### Currency Exchange Service

GET http://localhost:8000/currency-exchange/from/USD/to/INR

### Currency Conversion Service

GET http://localhost:8100/currency-conversion/from/USD/to/INR/quantity/10
###
GET http://localhost:8100/currency-conversion-feign/from/USD/to/INR/quantity/10

### Eureka
GET http://localhost:8761/

### API GATEWAY

### these won't work anymore
GET http://localhost:8765/CURRENCY-EXCHANGE-SERVICE/currency-exchange/from/USD/to/INR
###
GET http://localhost:8765/CURRENCY-CONVERSION-SERVICE/currency-conversion/from/USD/to/INR/quantity/10


### the actual routes working:
GET http://localhost:8765/currency-exchange/from/USD/to/INR
###
GET http://localhost:8765/currency-conversion/from/USD/to/INR/quantity/10

###
GET http://localhost:8765/get
